export const BLOG_POSTS = [
  {
    slug: 'bridal-beauty-timeline',
    title: 'Complete Bridal Beauty Timeline — When to Start Prep Before Your Wedding',
    description: 'A month-by-month beauty preparation guide for Karachi brides, from skincare routines to the final bridal trial.',
    date: '2026-05-10',
    lastModified: '2026-05-10',
    readTime: '8 min read',
    category: 'Bridal',
    content: [
      { type: 'p', text: 'Your wedding day is one of the most photographed days of your life. Every bride deserves to look and feel her absolute best — but that kind of radiance doesn\'t happen overnight. At Farwa Beauty Salon in PECHS Block 2, Karachi, we\'ve helped hundreds of brides prepare for their big day since 2008. Here\'s the timeline we recommend.' },
      { type: 'h2', text: '6 Months Before: Start Your Skincare Routine' },
      { type: 'p', text: 'Begin with a professional facial consultation. Our aestheticians will assess your skin type and create a customised plan. For Karachi\'s humid climate, we typically recommend monthly HD Whitening Facials (Rs 3,000) or Janssen Whitening Facials (Rs 5,500) to build a luminous base. Consistency is key — your skin needs time to respond to treatments.' },
      { type: 'h2', text: '3 Months Before: Hair Treatments & Colour Planning' },
      { type: 'p', text: 'If you\'re planning a colour change, now is the time. This gives you enough room for adjustments. Book a Wellaplex treatment (Rs 3,000) to strengthen your hair before any chemical processes. If hair fall is a concern, start a monthly Hair Fall Treatment with Ampule (Rs 3,000) — three sessions can make a visible difference.' },
      { type: 'h2', text: '1 Month Before: Bridal Trial' },
      { type: 'p', text: 'This is non-negotiable. A bridal trial lets you see the complete look — makeup, hair, dupatta draping — in real lighting. You\'ll get reference photos so both you and your artist are aligned. At Farwa, trials include a full consultation to fine-tune every detail. Many brides discover they want a slightly different lip shade or brow shape than they initially imagined.' },
      { type: 'h2', text: '1 Week Before: Final Prep Services' },
      { type: 'p', text: 'Schedule your full-body wax (Rica or honey), bleach, and a relaxing full-body massage. Don\'t try any new products or treatments this close to the date. Stick with what\'s worked during your preparation months. A Loreal Face Polish (Rs 900) gives a beautiful natural glow without any risk of reaction.' },
      { type: 'h2', text: 'The Day Before: Rest' },
      { type: 'p', text: 'Hydrate, sleep early, and trust the preparation you\'ve done. Your skin is ready, your trial was perfect, and tomorrow you\'ll be the most beautiful bride in Karachi.' },
      { type: 'h2', text: 'Book Your Bridal Consultation' },
      { type: 'p', text: 'Every bride\'s journey is different. WhatsApp us at +92 322 2782254 to start planning your personalised bridal beauty timeline. We\'ll guide you every step of the way.' },
    ],
  },
  {
    slug: 'skincare-mistakes-karachi-summer',
    title: '5 Skincare Mistakes Karachi Women Make in Summer',
    description: 'Avoid these common skincare errors that Karachi\'s heat and humidity make worse. Expert tips from our aestheticians.',
    date: '2026-05-05',
    lastModified: '2026-05-05',
    readTime: '6 min read',
    category: 'Skincare',
    content: [
      { type: 'p', text: 'Karachi\'s summer is relentless — the humidity, the heat, the dust. Your skincare routine needs to adapt, but many women make the same mistakes year after year. After 17+ years of treating Karachi skin, here\'s what we see most often at Farwa Beauty Salon.' },
      { type: 'h2', text: '1. Skipping Moisturiser Because "It\'s Too Hot"' },
      { type: 'p', text: 'This is the biggest myth. Humidity doesn\'t mean your skin is hydrated. Skipping moisturiser triggers your sebaceous glands to overcompensate — producing more oil, more breakouts, more texture. Switch to a lightweight, water-based moisturiser instead of going without.' },
      { type: 'h2', text: '2. Over-Washing Your Face' },
      { type: 'p', text: 'Washing more than twice a day strips your skin barrier. When you feel oily at 3pm, blot with a tissue or use micellar water instead. Your cleanser should be gentle and pH-balanced — harsh soaps worsen the very oiliness you\'re trying to control.' },
      { type: 'h2', text: '3. Ignoring Sunscreen Under Dupatta' },
      { type: 'p', text: 'Fabric doesn\'t block UV. You need SPF 30+ every single day, even if you\'re covered. Karachi\'s UV index regularly hits 10+ in summer. Choose a matte-finish sunscreen that won\'t feel heavy — reapply every 3 hours if you\'re outdoors.' },
      { type: 'h2', text: '4. DIY Bleaching Without Patch Testing' },
      { type: 'p', text: 'Home bleach kits are tempting in summer when you want that quick brightening effect. But without a patch test, you\'re risking burns and pigmentation — especially on heat-sensitised skin. Professional bleach treatments like our Loreal Whitening Face Bleach (Rs 650) are formulated and timed correctly for your skin type.' },
      { type: 'h2', text: '5. Waiting Too Long Between Facials' },
      { type: 'p', text: 'In summer, your pores accumulate more debris faster. A monthly facial isn\'t a luxury — it\'s maintenance. Our Acne Facial (Rs 1,800) and HD Cleansing (Rs 1,700) are specifically designed for congested summer skin. They clear what your daily cleanser can\'t reach.' },
      { type: 'h2', text: 'Get a Summer Skin Assessment' },
      { type: 'p', text: 'Not sure what your skin needs? Book a consultation at our PECHS Block 2 studio. We\'ll build a summer routine that actually works for Karachi weather. WhatsApp us at +92 322 2782254.' },
    ],
  },
  {
    slug: 'threading-vs-waxing',
    title: 'Threading vs Waxing: Which Is Better for Your Skin Type?',
    description: 'A detailed comparison of threading and waxing for facial and body hair removal — pros, cons, and expert recommendations.',
    date: '2026-04-28',
    lastModified: '2026-04-28',
    readTime: '5 min read',
    category: 'Guide',
    content: [
      { type: 'p', text: 'It\'s one of the most common questions we get at Farwa Beauty Salon: "Should I thread or wax?" The answer depends on the area being treated, your skin sensitivity, and what results you\'re after. Here\'s an honest breakdown from our team.' },
      { type: 'h2', text: 'Threading: Precision for the Face' },
      { type: 'p', text: 'Threading uses a twisted cotton thread to lift hair from the follicle. It\'s the gold standard for eyebrows because it offers unmatched precision — individual hairs can be targeted without affecting surrounding skin. At Farwa, our Eyebrow Threading (Rs 200) takes about 10 minutes and gives clean, architectural brows.' },
      { type: 'p', text: 'Best for: Eyebrows, upper lip, forehead, chin, and sideburns. Ideal for sensitive or acne-prone skin because no chemicals or heat touch the skin.' },
      { type: 'h2', text: 'Waxing: Speed for Larger Areas' },
      { type: 'p', text: 'Waxing removes hair in strips, making it far more efficient for arms, legs, and body. Rica hot wax is gentler on sensitive areas (face, bikini) because it grips hair without pulling skin. Honey wax is effective and affordable for larger body areas like Full Legs (Rs 1,200) or Full Body (Rs 2,800).' },
      { type: 'p', text: 'Best for: Arms, legs, back, underarms, and full body. Waxing also lightly exfoliates, leaving skin smoother than threading.' },
      { type: 'h2', text: 'When to Choose What' },
      { type: 'p', text: 'For facial hair: threading wins on precision and gentleness. For body hair: waxing wins on speed and coverage. Many of our regular clients combine both — threading for brows and upper lip, waxing for everything else.' },
      { type: 'h2', text: 'What About Skin Reactions?' },
      { type: 'p', text: 'Threading causes minimal redness that fades in 30 minutes. Waxing can cause temporary redness for 1-2 hours, especially on first visits. Rica wax minimises irritation compared to traditional strip wax. If you have extremely sensitive or rosacea-prone skin, threading is the safer choice for facial areas.' },
      { type: 'h2', text: 'Try Both and Decide' },
      { type: 'p', text: 'Everyone\'s skin responds differently. The best way to know is to experience both with trained professionals. Book a session at Farwa Beauty Salon — we\'ll guide you based on your skin type and preferences. WhatsApp us at +92 322 2782254.' },
    ],
  },
  {
    slug: 'make-manicure-last-two-weeks',
    title: 'How to Make Your Manicure Last 2 Weeks',
    description: 'Professional tips to extend the life of your salon manicure — from nail prep to daily habits that prevent chipping.',
    date: '2026-04-20',
    lastModified: '2026-04-20',
    readTime: '4 min read',
    category: 'Nails',
    content: [
      { type: 'p', text: 'You just got a beautiful manicure at the salon and within three days it\'s chipping. Sound familiar? The problem usually isn\'t the polish — it\'s what happens before and after application. Here\'s how to get a full two weeks out of your next manicure.' },
      { type: 'h2', text: '1. Prep Matters More Than Polish' },
      { type: 'p', text: 'Oil on your nail plate is the number one enemy of adhesion. Before polish, nails should be clean, dry, and lightly buffed. At Farwa Beauty Salon, our manicure services (starting from Rs 900) always include proper nail preparation — filing, cuticle care, and dehydration of the nail plate.' },
      { type: 'h2', text: '2. Always Use Base Coat' },
      { type: 'p', text: 'Base coat isn\'t optional. It creates a bonding layer between your natural nail and the colour. Without it, polish lifts from the edges within 48 hours. A good base coat also prevents staining, especially with darker reds and berries.' },
      { type: 'h2', text: '3. Cap the Free Edge' },
      { type: 'p', text: 'This is the trick most people miss at home. When applying colour and top coat, swipe a thin layer across the tip of the nail. This "caps" the edge and prevents water from getting under the polish — the main cause of tip chipping.' },
      { type: 'h2', text: '4. Wear Gloves for Chores' },
      { type: 'p', text: 'Hot water, detergent, and scrubbing are your manicure\'s worst enemies. Keep rubber gloves by the sink. This one habit alone can double the life of your polish. The same applies to hand sanitiser — the alcohol dries out polish and makes it brittle.' },
      { type: 'h2', text: '5. Refresh With Top Coat on Day 4' },
      { type: 'p', text: 'Apply a thin layer of top coat on day 3 or 4. This refreshes the shine and adds another protective barrier. It takes 2 minutes and can extend your manicure by nearly a week.' },
      { type: 'h2', text: 'Upgrade to a Longer-Lasting Option' },
      { type: 'p', text: 'If you need guaranteed longevity, our Paraffin Manicure (Rs 1,300) or SPA Manicure (Rs 1,400) include conditioning treatments that keep nails healthy and polish adherent for longer. For special occasions, French Manicure (Rs 1,600) with a gel-quality top coat is our most durable finish.' },
      { type: 'p', text: 'Book your next manicure at Farwa Beauty Salon, PECHS Block 2. WhatsApp us at +92 322 2782254.' },
    ],
  },
]
