export const BLOG_POSTS = [
  {
    slug: 'bridal-beauty-timeline',
    title: 'Complete Bridal Beauty Timeline — When to Start Prep Before Your Wedding',
    description: 'A month-by-month beauty preparation guide for Karachi brides, from skincare routines to the final bridal trial.',
    featuredImage: '/bridal.jpg',
    date: '2026-05-10',
    lastModified: '2026-05-10',
    readTime: '8 min read',
    category: 'Bridal',
    content: [
      { type: 'p', text: 'Your wedding day is one of the most photographed days of your life. Every bride deserves to look and feel her absolute best — but that kind of radiance doesn\'t happen overnight. At Farwa Beauty Salon in PECHS Block 2, Karachi, we\'ve helped hundreds of brides prepare for their big day since 2008. Here\'s the timeline we recommend.' },
      { type: 'h2', text: '6 Months Before: Start Your Skincare Routine' },
      { type: 'p', text: 'Begin with a professional facial consultation. Our aestheticians will assess your skin type and create a customised plan. For Karachi\'s humid climate, we typically recommend monthly HD Whitening Facials (Rs 3,000) or Janssen Whitening Facials (Rs 5,500) to build a luminous base. Consistency is key — your skin needs time to respond to treatments.' },
      { type: 'h2', text: '3 Months Before: Hair Treatments & Colour Planning' },
      { type: 'p', text: 'If you\'re planning a colour change, now is the time. This gives you enough room for adjustments. Book a Wellaplex treatment (Rs 3,000) to strengthen your hair before any chemical processes. If hair fall is a concern, start a monthly Hair Fall Treatment with Ampule (Rs 3,000) — three sessions can make a visible difference.' },
      { type: 'h2', text: '1 Month Before: Bridal Trial' },
      { type: 'p', text: 'This is non-negotiable. A bridal trial lets you see the complete look — makeup, hair, dupatta draping — in real lighting. You\'ll get reference photos so both you and your artist are aligned. At Farwa, trials include a full consultation to fine-tune every detail. Many brides discover they want a slightly different lip shade or brow shape than they initially imagined.' },
      { type: 'h2', text: '1 Week Before: Final Prep Services' },
      { type: 'p', text: 'Schedule your full-body wax (Rica or honey), bleach, and a relaxing full-body massage. Don\'t try any new products or treatments this close to the date. Stick with what\'s worked during your preparation months. A Loreal Face Polish (Rs 900) gives a beautiful natural glow without any risk of reaction.' },
      { type: 'h2', text: 'The Day Before: Rest' },
      { type: 'p', text: 'Hydrate, sleep early, and trust the preparation you\'ve done. Your skin is ready, your trial was perfect, and tomorrow you\'ll be the most beautiful bride in Karachi.' },
      { type: 'h2', text: 'Book Your Bridal Consultation' },
      { type: 'p', text: 'Every bride\'s journey is different. WhatsApp us at +92 322 2782254 to start planning your personalised bridal beauty timeline. We\'ll guide you every step of the way.' },
    ],
  },
  {
    slug: 'skincare-mistakes-karachi-summer',
    title: '5 Skincare Mistakes Karachi Women Make in Summer',
    description: 'Avoid these common skincare errors that Karachi\'s heat and humidity make worse. Expert tips from our aestheticians.',
    featuredImage: '/glow3.jpg',
    date: '2026-05-05',
    lastModified: '2026-05-05',
    readTime: '6 min read',
    category: 'Skincare',
    content: [
      { type: 'p', text: 'Karachi\'s summer is relentless — the humidity, the heat, the dust. Your skincare routine needs to adapt, but many women make the same mistakes year after year. After 17+ years of treating Karachi skin, here\'s what we see most often at Farwa Beauty Salon.' },
      { type: 'h2', text: '1. Skipping Moisturiser Because "It\'s Too Hot"' },
      { type: 'p', text: 'This is the biggest myth. Humidity doesn\'t mean your skin is hydrated. Skipping moisturiser triggers your sebaceous glands to overcompensate — producing more oil, more breakouts, more texture. Switch to a lightweight, water-based moisturiser instead of going without.' },
      { type: 'h2', text: '2. Over-Washing Your Face' },
      { type: 'p', text: 'Washing more than twice a day strips your skin barrier. When you feel oily at 3pm, blot with a tissue or use micellar water instead. Your cleanser should be gentle and pH-balanced — harsh soaps worsen the very oiliness you\'re trying to control.' },
      { type: 'h2', text: '3. Ignoring Sunscreen Under Dupatta' },
      { type: 'p', text: 'Fabric doesn\'t block UV. You need SPF 30+ every single day, even if you\'re covered. Karachi\'s UV index regularly hits 10+ in summer. Choose a matte-finish sunscreen that won\'t feel heavy — reapply every 3 hours if you\'re outdoors.' },
      { type: 'h2', text: '4. DIY Bleaching Without Patch Testing' },
      { type: 'p', text: 'Home bleach kits are tempting in summer when you want that quick brightening effect. But without a patch test, you\'re risking burns and pigmentation — especially on heat-sensitised skin. Professional bleach treatments like our Loreal Whitening Face Bleach (Rs 650) are formulated and timed correctly for your skin type.' },
      { type: 'h2', text: '5. Waiting Too Long Between Facials' },
      { type: 'p', text: 'In summer, your pores accumulate more debris faster. A monthly facial isn\'t a luxury — it\'s maintenance. Our Acne Facial (Rs 1,800) and HD Cleansing (Rs 1,700) are specifically designed for congested summer skin. They clear what your daily cleanser can\'t reach.' },
      { type: 'h2', text: 'Get a Summer Skin Assessment' },
      { type: 'p', text: 'Not sure what your skin needs? Book a consultation at our PECHS Block 2 studio. We\'ll build a summer routine that actually works for Karachi weather. WhatsApp us at +92 322 2782254.' },
    ],
  },
  {
    slug: 'threading-vs-waxing',
    title: 'Threading vs Waxing: Which Is Better for Your Skin Type?',
    description: 'A detailed comparison of threading and waxing for facial and body hair removal — pros, cons, and expert recommendations.',
    featuredImage: '/threading.jpg',
    date: '2026-04-28',
    lastModified: '2026-04-28',
    readTime: '5 min read',
    category: 'Guide',
    content: [
      { type: 'p', text: 'It\'s one of the most common questions we get at Farwa Beauty Salon: "Should I thread or wax?" The answer depends on the area being treated, your skin sensitivity, and what results you\'re after. Here\'s an honest breakdown from our team.' },
      { type: 'h2', text: 'Threading: Precision for the Face' },
      { type: 'p', text: 'Threading uses a twisted cotton thread to lift hair from the follicle. It\'s the gold standard for eyebrows because it offers unmatched precision — individual hairs can be targeted without affecting surrounding skin. At Farwa, our Eyebrow Threading (Rs 200) takes about 10 minutes and gives clean, architectural brows.' },
      { type: 'p', text: 'Best for: Eyebrows, upper lip, forehead, chin, and sideburns. Ideal for sensitive or acne-prone skin because no chemicals or heat touch the skin.' },
      { type: 'h2', text: 'Waxing: Speed for Larger Areas' },
      { type: 'p', text: 'Waxing removes hair in strips, making it far more efficient for arms, legs, and body. Rica hot wax is gentler on sensitive areas (face, bikini) because it grips hair without pulling skin. Honey wax is effective and affordable for larger body areas like Full Legs (Rs 1,200) or Full Body (Rs 2,800).' },
      { type: 'p', text: 'Best for: Arms, legs, back, underarms, and full body. Waxing also lightly exfoliates, leaving skin smoother than threading.' },
      { type: 'h2', text: 'When to Choose What' },
      { type: 'p', text: 'For facial hair: threading wins on precision and gentleness. For body hair: waxing wins on speed and coverage. Many of our regular clients combine both — threading for brows and upper lip, waxing for everything else.' },
      { type: 'h2', text: 'What About Skin Reactions?' },
      { type: 'p', text: 'Threading causes minimal redness that fades in 30 minutes. Waxing can cause temporary redness for 1-2 hours, especially on first visits. Rica wax minimises irritation compared to traditional strip wax. If you have extremely sensitive or rosacea-prone skin, threading is the safer choice for facial areas.' },
      { type: 'h2', text: 'Try Both and Decide' },
      { type: 'p', text: 'Everyone\'s skin responds differently. The best way to know is to experience both with trained professionals. Book a session at Farwa Beauty Salon — we\'ll guide you based on your skin type and preferences. WhatsApp us at +92 322 2782254.' },
    ],
  },
  {
    slug: 'make-manicure-last-two-weeks',
    title: 'How to Make Your Manicure Last 2 Weeks',
    description: 'Professional tips to extend the life of your salon manicure — from nail prep to daily habits that prevent chipping.',
    featuredImage: '/pedicure.jpg',
    date: '2026-04-20',
    lastModified: '2026-04-20',
    readTime: '4 min read',
    category: 'Nails',
    content: [
      { type: 'p', text: 'You just got a beautiful manicure at the salon and within three days it\'s chipping. Sound familiar? The problem usually isn\'t the polish — it\'s what happens before and after application. Here\'s how to get a full two weeks out of your next manicure.' },
      { type: 'h2', text: '1. Prep Matters More Than Polish' },
      { type: 'p', text: 'Oil on your nail plate is the number one enemy of adhesion. Before polish, nails should be clean, dry, and lightly buffed. At Farwa Beauty Salon, our manicure services (starting from Rs 900) always include proper nail preparation — filing, cuticle care, and dehydration of the nail plate.' },
      { type: 'h2', text: '2. Always Use Base Coat' },
      { type: 'p', text: 'Base coat isn\'t optional. It creates a bonding layer between your natural nail and the colour. Without it, polish lifts from the edges within 48 hours. A good base coat also prevents staining, especially with darker reds and berries.' },
      { type: 'h2', text: '3. Cap the Free Edge' },
      { type: 'p', text: 'This is the trick most people miss at home. When applying colour and top coat, swipe a thin layer across the tip of the nail. This "caps" the edge and prevents water from getting under the polish — the main cause of tip chipping.' },
      { type: 'h2', text: '4. Wear Gloves for Chores' },
      { type: 'p', text: 'Hot water, detergent, and scrubbing are your manicure\'s worst enemies. Keep rubber gloves by the sink. This one habit alone can double the life of your polish. The same applies to hand sanitiser — the alcohol dries out polish and makes it brittle.' },
      { type: 'h2', text: '5. Refresh With Top Coat on Day 4' },
      { type: 'p', text: 'Apply a thin layer of top coat on day 3 or 4. This refreshes the shine and adds another protective barrier. It takes 2 minutes and can extend your manicure by nearly a week.' },
      { type: 'h2', text: 'Upgrade to a Longer-Lasting Option' },
      { type: 'p', text: 'If you need guaranteed longevity, our Paraffin Manicure (Rs 1,300) or SPA Manicure (Rs 1,400) include conditioning treatments that keep nails healthy and polish adherent for longer. For special occasions, French Manicure (Rs 1,600) with a gel-quality top coat is our most durable finish.' },
      { type: 'p', text: 'Book your next manicure at Farwa Beauty Salon, PECHS Block 2. WhatsApp us at +92 322 2782254.' },
    ],
  },
  {
    slug: 'best-bridal-makeup-packages-karachi-2026',
    title: 'Best Bridal Makeup Packages in Karachi 2026 — What to Expect and How to Choose',
    description: 'A complete guide to bridal makeup packages in Karachi for 2026 — what\'s included, how much to budget, when to book, and why a trial matters.',
    featuredImage: '/bridal2.jpg',
    date: '2026-05-12',
    lastModified: '2026-05-12',
    readTime: '7 min read',
    category: 'Bridal',
    content: [
      { type: 'p', text: 'Your wedding day deserves a look that is uniquely, unmistakably you. In a city with hundreds of salons, choosing the right bridal makeup package in Karachi can feel overwhelming. Price ranges vary wildly, inclusions differ from studio to studio, and the wrong choice can leave you with regret on the most photographed day of your life. At Farwa Beauty Salon in PECHS Block 2, we have been styling Karachi brides since 2008 — here is everything you need to know before you book.' },
      { type: 'h2', text: 'What Is Typically Included in a Bridal Package?' },
      { type: 'p', text: 'A standard bridal makeup package in Karachi usually covers the base makeup application (foundation, concealer, contouring, setting), eye makeup with lashes, lip colour, brow detailing, and dupatta or hijab draping. Higher-tier packages add hairstyling, jewellery setting, a bridal trial session, and touch-up service at the venue. At Farwa, our Bridal Packages begin at Rs 15,000 for nikah looks and go up to Rs 50,000+ for full multi-event coverage including mehndi, barat, and walima looks.' },
      { type: 'h2', text: 'Price Ranges to Expect in 2026' },
      { type: 'p', text: 'Budget-friendly packages in Karachi typically start around Rs 8,000–15,000 for a single-event bridal look. Mid-range studios like ours charge Rs 15,000–35,000 and include a trial, premium products, and personalised consultations. High-end packages from celebrity artists can run Rs 50,000–150,000 or more. The key difference is not always the products — it is the experience, the attention to detail, and the time dedicated to you.' },
      { type: 'h2', text: 'Why the Bridal Trial Is Non-Negotiable' },
      { type: 'p', text: 'A trial is your insurance policy. It lets you see the full look — makeup, hair, dupatta — in real lighting, on your actual skin. You get reference photos so you and your artist are perfectly aligned on wedding day. At Farwa, we schedule trials at least two to four weeks before the event. Many brides discover they want a slightly warmer base or a different lip shade than they initially imagined. Better to find out at a trial than on the barat stage.' },
      { type: 'h2', text: 'When Should You Book?' },
      { type: 'p', text: 'Peak wedding season in Karachi runs from October through March. If your wedding falls in this window, book your bridal package at least two to three months in advance. Off-season weddings (April through September) give you more flexibility, but we still recommend locking in your dates at least six weeks ahead. Early booking also ensures time for a proper skincare preparation plan — facials, peels, and treatments that build a luminous base over weeks.' },
      { type: 'h2', text: 'How to Choose the Right Studio' },
      { type: 'p', text: 'Look at recent work, not just portfolio highlights from years ago. Ask about the specific products used — MAC, Huda Beauty, Charlotte Tilbury, and Kryolan are reliable choices for Karachi humidity. Read Facebook and Google reviews from real brides. Visit the studio in person to check hygiene and ambiance. A good bridal artist will listen to your vision, offer honest advice, and never rush the process.' },
      { type: 'h2', text: 'Questions Every Bride Should Ask' },
      { type: 'p', text: 'Before signing any package, ask: What exactly is included? Is the trial free or separate? Do you travel to venues, and is there a travel fee? What happens if I need touch-ups during the event? Can I see your most recent bridal work? How many brides do you take per day? At Farwa, we limit ourselves to one bride per event day — your day is entirely yours.' },
      { type: 'h2', text: 'Ready to Start Planning?' },
      { type: 'p', text: 'Every bride\'s journey is different, and we love helping you find the perfect look. WhatsApp us at +92 322 2782254 to schedule your bridal consultation at our PECHS Block 2 studio. Browse our full Bridal services to see what we offer.' },
    ],
  },
  {
    slug: 'gold-facial-vs-whitening-facial',
    title: 'Gold Facial vs Whitening Facial — Which One Is Right for Your Skin?',
    description: 'A detailed comparison of gold facials and whitening facials — ingredients, benefits, ideal skin types, and pricing at Farwa Beauty Salon Karachi.',
    featuredImage: '/glow.jpg',
    date: '2026-05-08',
    lastModified: '2026-05-08',
    readTime: '6 min read',
    category: 'Skincare',
    content: [
      { type: 'p', text: 'Walk into any salon in Karachi and you will find gold facials and whitening facials near the top of the menu. Both promise glowing skin, but they work in fundamentally different ways and suit different skin concerns. At Farwa Beauty Salon in PECHS Block 2, these two treatments are among our most requested — here is an honest comparison to help you choose.' },
      { type: 'h2', text: 'What Is a Gold Facial?' },
      { type: 'p', text: 'A gold facial uses products infused with colloidal gold particles. Gold has been used in skincare for centuries — Cleopatra reportedly slept in a gold mask. In modern formulations, the gold particles stimulate blood circulation, promote cell renewal, and give skin a warm, luminous finish. Our Gold Facial at Farwa (Rs 2,500) includes deep cleansing, gold-infused serum, a gold sheet mask, and a finishing moisturiser. The entire session takes about 60 to 75 minutes.' },
      { type: 'h2', text: 'What Is a Whitening Facial?' },
      { type: 'p', text: 'Whitening facials target uneven skin tone, dark spots, sun damage, and dullness. They use active ingredients like vitamin C, kojic acid, arbutin, and niacinamide to inhibit melanin production and brighten existing pigmentation. Our HD Whitening Facial (Rs 3,000) and Janssen Whitening Facial (Rs 5,500) are formulated specifically for South Asian skin tones and Karachi\'s intense UV exposure. Sessions run 60 to 90 minutes depending on the protocol.' },
      { type: 'h2', text: 'Which Skin Types Benefit Most?' },
      { type: 'p', text: 'Gold facials are ideal for mature, dry, or dull skin. The gold particles boost collagen production and restore radiance — perfect for women over 30 who want that "lit from within" glow. Whitening facials suit oily, combination, or pigmentation-prone skin. If you struggle with melasma, post-acne marks, or uneven tone from sun exposure, the whitening protocol will deliver more targeted results.' },
      { type: 'h2', text: 'Results and Frequency' },
      { type: 'p', text: 'A single gold facial gives an immediate glow that lasts about a week — making it a popular pre-event choice for weddings and parties. For lasting anti-aging benefits, we recommend one session every four to six weeks. Whitening facials show cumulative results. The first session brightens noticeably, but the real transformation happens after three to four monthly sessions as melanin production steadily decreases.' },
      { type: 'h2', text: 'Price Comparison at Farwa Beauty Salon' },
      { type: 'p', text: 'Our Gold Facial starts at Rs 2,500. Whitening facials range from Rs 3,000 (HD Whitening) to Rs 5,500 (Janssen Whitening) depending on the product line. Both represent excellent value compared to Karachi averages — and all our facials include a complimentary skin assessment so you never pay for a treatment that is not right for you.' },
      { type: 'h2', text: 'Can You Combine Both?' },
      { type: 'p', text: 'Yes — alternating between the two is one of our favourite protocols for brides. We typically recommend a whitening facial one month, followed by a gold facial the next. This addresses pigmentation while maintaining that warm glow. Your aesthetician at Farwa will design a schedule based on your skin goals and timeline.' },
      { type: 'h2', text: 'Book Your Skin Consultation' },
      { type: 'p', text: 'Not sure which facial is right for you? Let our team assess your skin in person. WhatsApp us at +92 322 2782254 to book at our PECHS Block 2 studio. Explore our full Facials menu for all available treatments and pricing.' },
    ],
  },
  {
    slug: 'complete-guide-hair-treatments-karachi',
    title: 'Complete Guide to Hair Treatments in Karachi — From Keratin to Protein',
    description: 'Everything you need to know about professional hair treatments in Karachi — keratin, protein, hair spa, and more with pricing and aftercare tips.',
    featuredImage: '/hairtreatment.jpg',
    date: '2026-05-03',
    lastModified: '2026-05-03',
    readTime: '7 min read',
    category: 'Hair',
    content: [
      { type: 'p', text: 'Karachi\'s water, humidity, dust, and sun create a perfect storm for damaged hair. Whether you are battling frizz, breakage, hair fall, or just general dullness, professional hair treatments can transform your locks in a single session. At Farwa Beauty Salon in PECHS Block 2, we have been treating Karachi hair since 2008 — here is our complete guide to the most popular treatments and how to choose the right one.' },
      { type: 'h2', text: 'Keratin Treatment' },
      { type: 'p', text: 'Keratin treatments coat each hair strand with a protective protein layer, eliminating frizz and adding mirror-like shine. The treatment takes two to three hours and results last three to five months depending on your hair care routine. Keratin is ideal for women with thick, curly, or frizzy hair who want smooth, manageable locks without daily straightening. At Farwa, our hair treatments start at Rs 2,000 for protein repair, with keratin smoothing available depending on hair length and density.' },
      { type: 'h2', text: 'Protein Treatment' },
      { type: 'p', text: 'If your hair feels elastic, gummy, or breaks easily when wet, it likely needs protein. Protein treatments like our Hair Fall Treatment with Ampule (Rs 3,000) replenish the structural building blocks of the hair shaft. Unlike keratin, protein treatments work from inside the strand rather than coating the surface. They are perfect for chemically treated, coloured, or heat-damaged hair. Results are cumulative — we recommend a session every four to six weeks for best results.' },
      { type: 'h2', text: 'Hair Spa' },
      { type: 'p', text: 'A professional hair spa combines deep conditioning with scalp massage and steam therapy. It is the gentlest option and works for all hair types. Our hair spa treatments address dryness, dandruff, and scalp tension. The steam opens hair cuticles so the conditioning mask penetrates deeply. Sessions take about 45 to 60 minutes and leave hair noticeably softer immediately. Think of a hair spa as the maintenance treatment — ideal monthly or between more intensive keratin or protein sessions.' },
      { type: 'h2', text: 'Wellaplex and Bond Repair' },
      { type: 'p', text: 'If you colour or bleach your hair regularly, Wellaplex (Rs 3,000 at Farwa) is essential. It works at the molecular level to rebuild the disulphide bonds that chemical processing breaks. This is not a surface-level treatment — it genuinely repairs structural damage. We always recommend Wellaplex alongside any colouring service to protect hair integrity from the start.' },
      { type: 'h2', text: 'How to Choose the Right Treatment' },
      { type: 'p', text: 'Start by identifying your primary concern. Frizz and unmanageability? Go with keratin. Breakage and elasticity loss? Protein is your answer. General dryness and dullness? A hair spa will refresh you. Chemical damage from colouring? Wellaplex. If you are unsure, book a consultation at Farwa — we will assess your hair type, porosity, and damage level before recommending anything.' },
      { type: 'h2', text: 'Aftercare Tips for Longer-Lasting Results' },
      { type: 'p', text: 'Use a sulphate-free shampoo — sulphates strip treatments faster than anything else. Avoid washing hair for 48 to 72 hours after keratin. Limit heat styling to once or twice a week. Sleep on a silk or satin pillowcase to reduce friction. And most importantly, maintain your treatment schedule. Consistency is what separates okay results from transformative ones.' },
      { type: 'h2', text: 'Book Your Hair Consultation' },
      { type: 'p', text: 'Every head of hair is different, and cookie-cutter solutions rarely work. WhatsApp us at +92 322 2782254 to book a hair assessment at our PECHS Block 2 studio. Check out our full Hair & Hair Treatments menu for all services and pricing.' },
    ],
  },
  {
    slug: 'prepare-first-salon-visit-tips',
    title: 'How to Prepare for Your First Salon Visit — Tips for New Clients',
    description: 'First time visiting a beauty salon? Here\'s what to expect, how to communicate your needs, and tips to make the most of your experience.',
    featuredImage: '/massage.jpg',
    date: '2026-04-25',
    lastModified: '2026-04-25',
    readTime: '5 min read',
    category: 'Guide',
    content: [
      { type: 'p', text: 'Walking into a beauty salon for the first time can feel intimidating — especially if you are not sure what to expect, what to ask for, or how things work. Whether you are a college student booking your first facial, a bride-to-be exploring options, or someone who has simply never had the occasion, this guide will help you feel confident and prepared. At Farwa Beauty Salon in PECHS Block 2, Karachi, we welcome first-time visitors every week — here is what we wish everyone knew before their first appointment.' },
      { type: 'h2', text: 'Start With What You Want to Achieve' },
      { type: 'p', text: 'You do not need to know salon terminology to get great service. Simply describe what you want in your own words: "I want my eyebrows shaped but not too thin," "My skin looks dull and I want it to glow," or "I have a wedding in two weeks and need everything done." A good aesthetician will translate your goals into the right services. At Farwa, we always start with a brief consultation before any treatment.' },
      { type: 'h2', text: 'What to Expect When You Arrive' },
      { type: 'p', text: 'Most salons will greet you, ask your name, and seat you in the waiting area. You may be offered water or tea. A staff member will discuss what services you want, explain the process, and give you a price estimate before starting. At our PECHS Block 2 studio, the atmosphere is calm and unhurried — we never rush clients through services. If anything makes you uncomfortable during a treatment, speak up immediately. Your comfort is the priority.' },
      { type: 'h2', text: 'How to Communicate Your Preferences' },
      { type: 'p', text: 'Reference photos are incredibly helpful. If you want a specific brow shape, hair style, or nail colour, show a picture on your phone. Be honest about your skin sensitivities, allergies, or any medications you are taking — some treatments interact with retinoids, blood thinners, or acne medications. If you prefer a certain amount of hair removed or a specific pain threshold, say so upfront. There is no such thing as a silly question in a good salon.' },
      { type: 'h2', text: 'Hygiene Standards to Look For' },
      { type: 'p', text: 'Pay attention to cleanliness. Fresh towels for each client, sanitised tools, sealed wax sticks (never double-dipped), and clean workstations are non-negotiable. Threading cotton should be new. Wax applicators should be single-use. At Farwa, we follow strict hygiene protocols and are happy to show you our sanitisation process if you ask. A salon that gets defensive about hygiene questions is a red flag.' },
      { type: 'h2', text: 'Budgeting and Tipping' },
      { type: 'p', text: 'Ask for a price list before booking or check the salon\'s website. At Farwa, our threading starts at Rs 200 and facials range from Rs 900 to Rs 5,500 depending on the treatment. Tipping is appreciated but not mandatory in Pakistan — Rs 100 to 500 is a kind gesture depending on the service. If a staff member went above and beyond, a tip lets them know you noticed.' },
      { type: 'h2', text: 'After Your Visit' },
      { type: 'p', text: 'Avoid touching freshly threaded or waxed areas for a few hours. Skip heavy makeup immediately after a facial — let your skin breathe and absorb the treatment. Apply sunscreen before stepping out, especially after any brightening or exfoliating service. If you experience any unexpected reaction, contact the salon — a reputable place will always follow up.' },
      { type: 'h2', text: 'Book Your First Appointment' },
      { type: 'p', text: 'Everyone was a first-timer once, and we love welcoming new faces. WhatsApp us at +92 322 2782254 to book your first visit at Farwa Beauty Salon, PECHS Block 2, Karachi. Browse our Services page to explore our full menu — from threading to bridal packages, we have something for everyone.' },
    ],
  },
]
